### ISSUE TITLE
Keybinds

### ISSUE THREAD

**Issue by Vertex-Client** [Vertex-Client/Vertex-Client-PE#13]
We're working on keybind support. It will be compatible with external/hardware keyboards. The key for the TabGUI will be CTRL.

**Comment by Martin77Epic** [comment]
Meh add Buttons on Screen!

**Comment by Vertex-Client** [comment]
We will add a TabGUI/additional UI soon (unlike the ClickGUI, it's more like a popup on the left side of the screen which allows you to toggle mods fast)
