### ISSUE TITLE
Crashing bug

### ISSUE THREAD

**Issue by Bluestacker** [Vertex-Client/Vertex-Client-PE#14]
Hi, i'm using Minecraft pe 0.14.2, i tried using Toolbox and BlockLauncher 1.12.5 and don't work, the problem is opening the mod menu, and crash! :(

Regards.

**Comment by Vertex-Client** [comment]
Please make sure that you did the following things:
1. Don't open the menu while you're on the play screen.
2. Only open it in game.

**Comment by Bluestacker** [comment]
Thanks, other question, how to use this in multiplayer? block launcher blocks the app?

**Comment by Bluestacker** [comment]
BlockLauncher 1.12.5 don't works in my Tablet, works in ToolBox?

**Comment by Bluestacker** [comment]
Thanks :D
