### ISSUE TITLE
Vertex Client does not load up for me...

### ISSUE THREAD

**Issue by chdxtn** [Vertex-Client/Vertex-Client-PE#19]
I am not sure if it is because of my device or it's just the mod but before I updated my BlockLauncher Pro to 1.12.8,it loaded up fairly quickly and it didn't have that much bugs.It started a few days after I updated BL and when I updated Vertex Client to I think 1.3 Beta or maybe 1.3.1 Beta,I'm not sure because I forgot when this happened.

**Comment by Vertex-Client** [comment]
I'm also not sure. :/

**Comment by chdxtn** [comment]
I'll try it on Toolbox.I'll see if it works better...

**Comment by Vertex-Client** [comment]
Please try the following things now:
1. Remove the following file: com.mojang/minecraftpe/vertexclientpe.txt
2. Try the latest v1.0 (pre-release).

**Comment by chdxtn** [comment]
Issue fixed.Close Issue #19 for it has been fixed.
Looks like it was just a bug on BlockLaucher.
-Buga

**Comment by Vertex-Client** [comment]
Glad it works fine again!
Closing #19
