### ISSUE TITLE
Vertex Client pre3 don't open

### ISSUE THREAD

**Issue by ghost** [Vertex-Client/Vertex-Client-PE#20]
Vertex Client does not open because it says there is a new version, but I am using the latest (PRE 3) . I am using with toolbox beta 3

**Comment by ghost** [comment]
It Say :" Sorry this version of Vertex is not supporter anymore!  Please upgrade to the latest version" but I'm using v1.0 pre3 (lates)

**Comment by Vertex-Client** [comment]
I'm sorry, I forgot to edit the support file. I will fix it asap (it doesn't require a redownload). 😃
EDIT: It should be fixed now. :)
