### ISSUE TITLE
The game could crash when using Toolbox and/or leaving the game

### ISSUE THREAD

**Issue by dausruddin** [Vertex-Client/Vertex-Client-PE#25]
I have an issue while flying because account manager menu on the bottom is covering down button. And the top menu also sometimes clicked when I try to tap item in chest.

**Comment by Vertex-Client** [comment]
What do you mean with top menu? If you mean the hacks list: you can click through it, it's just an overlay.  You should be able to tap on items underneath it. In v1.1 the menu button will be shown in the corner instead of next to the corner.

**Comment by dausruddin** [comment]
I am sorry, seems that the top-right menu doesnt cover anything, idk why I said it covering items in chest xD.
Btw there is an Account Manager (AM) button down-right that exist most of the time, but sometimes it doesnt. (http://i.imgur.com/t28eiPHh.jpg). It covered.down button in fly mode, and xray button. 

Btw, where to get v1.1? I only see v1.0.1 as the latest. Even the the mod said I have the latest version.

**Comment by dausruddin** [comment]
Ok I took the script with latest commit and it seems to crash the game. It would stuck at building terrain and crashed. Im talking about server here, never tried it on local world.  I have tried a few different server and it crashed at building terrain. Sometimes it freeze the game for almost a minute, then crashed.

**Comment by Vertex-Client** [comment]
I will look into it. Thanks.

**Comment by dausruddin** [comment]
Addition, I am using Toolbox, never tried it with the Blocklauncher. Great mod btw :)

**Comment by dausruddin** [comment]
V1.1 still crashing on my side. Is there anything I can do to help you debug this? Im using toolbox

**Comment by Vertex-Client** [comment]
Send me the stack trace (report button on the crash dialog --> system information --> stack trace).

**Comment by dausruddin** [comment]
Hope this help.
http://i.imgur.com/3bzkXkC.png

**Comment by Vertex-Client** [comment]
Thanks for the report, I think I fixed it, along with these (other) fixes and improvements:
- Fixed an issue where the hacks list and TabGUI didn't always show up when using Toolbox
- Improved news bar width
- Improved Account Manager button size
- Fixed an issue where the game could crash when leaving a world

**Comment by Vertex-Client** [comment]
Could you test the latest commit cf64f9a?

**Comment by dausruddin** [comment]
Crashed when left a server. Tested on lbsg.
http://i.imgur.com/EgvqvJA.png

This is for crashing when I actuvated speedhack on server. Tested on my private server.
http://i.imgur.com/S4jr23d.png

**Comment by Vertex-Client** [comment]
I can fix the first one, the second one is too cryptic, it looks like it's a Toolbox bug since it should work on BlockLauncher.

**Comment by Vertex-Client** [comment]
Try to use the latest commit 

> e753819 - Fix another issue where the game could crash when leaving a world
