### ISSUE TITLE
No hacks work in multiplayer

### ISSUE THREAD

**Issue by DaMatrix** [Vertex-Client/Vertex-Client-PE#27]
Whenever i try to enable a hack in multiplayer, a popup appears with an error message and goes away too quickly to be read.  Will try to catch ss in a bit.

Server: PocketMine 0.15.4
Latest Toolbox and Vertex 1.1 (the one in releases)

**Comment by Vertex-Client** [comment]
Please send me a screenshot or at least an error/crash log.

**Comment by DaMatrix** [comment]
https://drive.google.com/folderview?id=0B-mktGE1eb5GZjRVb3hHRnV2SUk
After that Toolbox crashes.

**Comment by DaMatrix** [comment]
It does that on all hacks, ive tested them all.

**Comment by Vertex-Client** [comment]
Thanks, will try to fix this and eventually release v1.1.2.

**Comment by Vertex-Client** [comment]
Please send me the crash report too (report button --> system information --> stack trace).

**Comment by Vertex-Client** [comment]
Tested this on 0.15.3, no errors... I can't reproduce it.

**Comment by Vertex-Client** [comment]
Toolbox is probably broken...

**Comment by DaMatrix** [comment]
Seems to be fixed in 1.1.1, closing
