### ISSUE TITLE
Vertex client pro 

### ISSUE THREAD

**Issue by survivalkiller9** [Vertex-Client/Vertex-Client-PE#28]
Es geht nicht da steht ich soll pro Version zu V1.1.1 machen

**Comment by Vertex-Client** [comment]
Nein, es geht zu v1.1.1... Du sollst BlockLauncher/Toolbox's data 'clearen'. Ich wünsche dir ein schönes tag. :)

**Comment by survivalkiller9** [comment]
Aber wenn ich online gehe ist vertex weg kann es nicht sein das ihr online
Patch gemacht habt bei mcpe Master steht ich muss erst das Spiel öffnen ob
wohl es schon offen ist

Am 27.08.2016 12:13 schrieb "Vertex Client" notifications@github.com:

**Comment by Vertex-Client** [comment]
Don't use MCPE Master, it's not supported for online use.
