### ISSUE TITLE
KA doesn't work in multiplayer

### ISSUE THREAD

**Issue by Creeperface01** [Vertex-Client/Vertex-Client-PE#29]
KillAura doesn't work in multiplayer

**Comment by Vertex-Client** [comment]
Not an issue, closed #29.

**Comment by Creeperface01** [comment]
what? :D

**Comment by Creeperface01** [comment]
but it wont, will it?

**Comment by Vertex-Client** [comment]
Of course not, Entity.setHealth(healthAmount) doesn't work on multiplayer, since the health is controlled and checked on the server side.

**Comment by Creeperface01** [comment]
and what about some addon? :D

**Comment by Affannnn** [comment]
Drag op Aim Aura Is Working On Server

**Comment by Affannnn** [comment]
Copy That Code

**Comment by Creeperface01** [comment]
What

**Comment by Creeperface01** [comment]
Yes what about something like aim aura
