### ISSUE TITLE
Problem in 1.2

### ISSUE THREAD

**Issue by Affannnn** [Vertex-Client/Vertex-Client-PE#36]
Now You Crash Leaving Game
And You Can't Play Music On Server!!

**Comment by Vertex-Client** [comment]
That's weird... We'll look into it and make a v1.2.1 release if needed. Hope you have a great day! ;)
~peacestorm (Vertex (main) developer)

**Comment by Vertex-Client** [comment]
But please read the "How do I report an issue" next time since this issue isn't very good.

**Comment by Affannnn** [comment]
It's the same issues which were on 1.0.0

**Comment by Affannnn** [comment]
Ok next time I will read

**Comment by Vertex-Client** [comment]
Please send me a screenshot of the stack trace (report button -> system information -> stack trace).

**Comment by Affannnn** [comment]
Sorry I Don't What Is That However This Issues Are Same In 1.0.0 But It was fixed in 1.0.1

**Comment by Vertex-Client** [comment]
...
WHEN IT CRASHES A DIALOG SHOULD POPUP
TAP ON THE REPORT BUTTON
TAP ON SYSTEM INFORMATION
SCROLL UNTIL YOU SEE STACK TRACE AND TAP ON IT
...

**Comment by Affannnn** [comment]
However Am Closing This Because I Found A New Hack Which Have No Down Glide Which I Need So Closed!
