### ISSUE TITLE
Servers??

### ISSUE THREAD

**Issue by ICANTLOGINTOSERV** [Vertex-Client/Vertex-Client-PE#38]
So when i try to join a server with this client it crashes but when i use my other clients it works so what's going on??

**Comment by Vertex-Client** [comment]
We're trying to figure out what happened, but we didn't find it yet.

**Comment by Vertex-Client** [comment]
Everything works fine on BlockLauncher though.

**Comment by AutoGrind** [comment]
If your talking about it not working with "Toolbox" I remember it not working after the first "Summer update." I was able to reproduce this problem before "Toolbox" updated. Hope that helps trace steps back.
 I mentioned this already before this post which makes it redundant, if you'd like to merge or just delete mine to keep this in one place thats cool.
