### ISSUE TITLE
Cant login into servers

### ISSUE THREAD

**Issue by shadmarc** [Vertex-Client/Vertex-Client-PE#40]
Can't log into specific servers because the servers have replaced the / with a . before command and because of that vertex acts like I would like to run a command (the server on the screenshot is mineplex)
I suggest adding a switch to enable/disable the vertex commands :)
Mcpe version: 0.16.0.5
Launcher: toolbox
Device: lenovo A-7600
![screenshot_2016-11-02-14-45-59](https://cloud.githubusercontent.com/assets/23214214/19929375/b7ffef78-a10b-11e6-8877-57b3425aaa18.png)

**Comment by peacestorm** [comment]
Hey there, we don't understand your message since we already added a switch for that in v1.7. :)

**Comment by shadmarc** [comment]
Oh, I got it working now thanks :D

**Comment by Vertex-Client** [comment]
No problem. :)
