### ISSUE TITLE
Kill aura Don't work in multiplayer

### ISSUE THREAD

**Issue by Bluestacker** [Vertex-Client/Vertex-Client-PE#42]
hey, kill aura don't kill players, please fix :(
Android version: 5.1 Lollipop
Vertex Client PE version: 1.7
MCPE version: 0.16.1
Launcher: Toolbox
Pro: yes
Device: Samsung J7

**Comment by DaMatrix** [comment]
It doesn't work on multiplayer 

Sent from my Samsung device

-------- Original message --------

**Comment by Vertex-Client** [comment]
This is normal, Killaura is not possible on multiplayer, you may be referring to Aimbot, we will add support for players once we get it working.

**Comment by DaMatrix** [comment]
Sorry, did that come across as me not knowing why it doesn't work on multiplayer? I know why :P

**Comment by Vertex-Client** [comment]
**Aimbot**
BlockLauncher status: blocks most mods, has always been like this since 0.11.x
Toolbox status: works properly for the current implementation, we didn't add player compatibility yet.

**Killaura**
Was never intended to work on multiplayer, we can't add a real Killaura yet.

**Comment by Vertex-Client** [comment]
I'm closing this issue for now.
