### ISSUE TITLE
Error Server Info mod

### ISSUE THREAD

**Issue by TeaserMC** [Vertex-Client/Vertex-Client-PE#47]
Error Server info mod in new commit

**Comment by TeaserMC** [comment]
Android version: 5.0.1
Vertex Client PE version: v2.2 beta
MCPE version: 1.0.4
Launcher: Toolbox
Pro: yes
Device: OPPO Neo 9

**Comment by Vertex-Client** [comment]
Please send the error message.

**Comment by TeaserMC** [comment]
How to upload pictures

**Comment by TeaserMC** [comment]
![screenshot_2017-03-12-22-27-12-35](https://cloud.githubusercontent.com/assets/26355537/23833077/467cf246-0773-11e7-8d44-34b2d2526af2.png)
![screenshot_2017-03-12-22-27-18-12](https://cloud.githubusercontent.com/assets/26355537/23833078/4d7b0074-0773-11e7-8119-06b872dbe200.png)

**Comment by Vertex-Client** [comment]
That's weird, I don't have that error...
At least not on BlockLauncher.

**Comment by TeaserMC** [comment]
What does this mean

**Comment by Vertex-Client** [comment]
Hmm, it also works on Toolbox for me.

**Comment by TeaserMC** [comment]
It work for you?

**Comment by TeaserMC** [comment]
I use the latest commit from you

**Comment by Vertex-Client** [comment]
Yes, it works, I didn't get the error. Only some wrong results, but not the error. But it's because we use a server status website, so it depends on the site too.

**Comment by TeaserMC** [comment]
I use mcpe version 1.0.4.11
I tried with multiple servers, and it did not work

**Comment by Vertex-Client** [comment]
Maybe it's because of your MCPE version, or your internet. But for me it works. We're sorry.
