### ISSUE TITLE
Possibly outdated application package reference for MCPE Master

### ISSUE THREAD

**Issue by CtrlAltCuteness** [Vertex-Client/Vertex-Client-PE#51]
I'll apologize for using the wrong format (second time today), but if my guess really is true, the package name changed for one of the ModPE-enabled Minecraft launchers.  
Searching `pname:com.mcbox.pesdkb.mcpelauncher` on the official Google Play Store didn't show anything for me while `pname:com.groundhog.mcpemaster` gives me the result for what I have currently installed. (I also seem to know how to force the launcher, at least for a previous version of it and MC:PE, to run mods... just not have them accessible from the launcher itself).

Best wishes,  
[\@CtrlAltCuteness](https://twitter.com/CtrlAltCuteness) (Twitter)

**Comment by Vertex-Client** [comment]
Hiya! If you decompile MCPE Master, you will find multiple packages in it, as the launcher is based on another one. The files required are most probably in the package which we use at the moment. We're not sure yet, and we don't really test on MCPE Master at the moment as the launcher is a bit buggy.

**Comment by CtrlAltCuteness** [comment]
Thank you for the info. I normally use BlockLauncher Pro for mods, yet it doesn't seem to work for me with Vertex. :(  
I must resort to the other alternative I know that does work... requiring BlockLauncher to be installed, oddly enough due to being a BlockLauncher Add-on (Toolbox for Minecraft: Pocket Edition).... yet I'm going to wait a bit as I already updated to 1.0.6 without a backup *facepalm*

**Comment by Vertex-Client** [comment]
Toolbox is an addon and a launcher in one. Launch Toolbox using its icon instead of using it as a BL addon.

**Comment by CtrlAltCuteness** [comment]
Sorry (no offense meant in my poor word choice), but yes I do that... I keep that BL Add-on disabled (keeps erroring on BL start), and when I start Toolbox as of recent it has complained of incompatible MC:PE (yet working fine ... haven't tested with 1.0.6 yet.... ... and I put myself on the beta channel to get *that* update?).

Thanks for the kindnees (also I apologize if my mental disability gets annoying).  
Future note: If I don't respond in a timely manner, check my profile's URL for my Twitter handle / page as I *should* get a notice that way (message me privately with the URLs to the ones needing to be checked by me or just the issue section here... or just say like `Friendly reminder: Check GitHub project issues you participated in.`).

**Comment by Vertex-Client** [comment]
Thanks for you reply. Toolbox for 1.0.6 is on its way.

**Comment by CtrlAltCuteness** [comment]
Oh... according to what I saw in the package data for at least MCPE Master... they overdone their stuff. (Unnecessary stuff, namely adverts, if one just wants to use ModPE or other features on the supported versions!)

**Comment by CtrlAltCuteness** [comment]
@Vertex-Client I'll just close this issue as it probably doesn't have much real need as I can see it at this time. Feel free to reopen if you think it is required (I'm doing this not as a "I lost" thing, which I did lose, but to clean up the open issues list from unnecessary issues).
