### ISSUE TITLE
MCPE's options.txt file in data folder instead of com.mojang/minecraftpe

### ISSUE THREAD

**Issue by 4sakurachan** [Vertex-Client/Vertex-Client-PE#52]
None of the txt files have been created (options.txt) and my game wont load any worlds

**Comment by Vertex-Client** [comment]
This only applies to versions above 1.0.4. We advise to not use 1.0.5/6 or 1.1.

**Comment by Vertex-Client** [comment]
Possible fix: make sure the storage setting is not set to internal!
