### ISSUE TITLE
Not an issue, just a question.

### ISSUE THREAD

**Issue by Nova-69** [Vertex-Client/Vertex-Client-PE#53]
Android version: 5.1.1 Lolipop
Vertex Client PE version: v2.3
MCPE version: 1.6
Launcher: Toolbox
Pro: yes
Device: Visual Land Prestige Elite 11Q

I just saw a new update for MCPE (v1.7) and I was wondering if Vertex Client supports that version, or if a update for Vertex will need to happen to support it. If you guys could awnser that would be great. Thanks! 😄

**Comment by Vertex-Client** [comment]
Hiya! We're sorry, but since Mojang decided to move the options.txt file into the data folder, we don't support 1.0.5+ at the moment.

**Comment by Nova-69** [comment]
Oh, that's too bad. Well, thanks for the response Vertex! :) So, when do you think the next update will come to add support for 1.0.5+?

**Comment by Vertex-Client** [comment]
We're not sure, but v2.3.1 is coming soon and we have no plans for support yet.

**Comment by Nova-69** [comment]
Oh, ok. Well, thanks for the help & info! :D Ima close this issue for now
