### ISSUE TITLE
Ok explain dis problem

### ISSUE THREAD

**Issue by OkHoldDaFckUp** [Vertex-Client/Vertex-Client-PE#55]
So I downloaded ur client and imported it to mcpe master,bloacklauncher and toolbox and the results are all fail.... I opened mcpe master first it loaded like a century(sarcasm) I found out that it downloaded pictures and when i activated pro it loads but the "fps" meter is 0 ZEROOOOOO after that crash more crash crashtastic mega crash and all crashin' stuff.So next i opened bl it didnt even started so i opened toolbox it was ok ok ok ok but when i pressed the vx button on the top its not working so i pressed it again but nothing happens i keep pressing it for 3 minutes but nothing happens only the version info of ur client is showing up and vanishing and repeat...whats this? Is it a bug or it just suck. i used your client when im 0.17.0 and it worked well now im using 1.0.6.0 and the launchers are updated. can u pls explain?

**Comment by OkHoldDaFckUp** [comment]
also all i can use is morph,dashboard,webbrowser and all stuff if u press and hold the vx button

**Comment by Vertex-Client** [comment]
Any errors? If the menu doesn't open, choose another menu style on the settings screen.

PS: We actually don't support any versions after 1.0.3.

**Comment by OkHoldDaFckUp** [comment]
ok thanks for the reply have a nice day devs

**Comment by Vertex-Client** [comment]
Thanks, I'll close the issue for now.
~peacestorm
