### ISSUE TITLE
Bug. Please help!!!

### ISSUE THREAD

**Issue by aboudshi-da7a** [Vertex-Client/Vertex-Client-PE#56]
![img_20170517_191438](https://cloud.githubusercontent.com/assets/28781095/26200763/3b2dcc0c-3b7c-11e7-958e-031bce9f9378.png)
Hey!
The client is awesome. I tried it for the first time on toolbox and it worked perfectly.
But when I opened toolbox again everything seems fine until I opened a world the Vertex Client gave me a message "null: Error: InternalError: Cannot convert InternalError: Can't find method android widget TextView.set Text (org.mozilla.javascript. Undefined) (Vertex Client PE.modpkg/ script/Vertex Client PE v2.3.jst 10368) to java.lang.Integer (Vertex Client PE.modpkg/script/Vertex Client PE v2.3.js#11640)"
You can find the message in the photo up.
When I click the Vertex button at the left corner, it gives me the same message but when I click again Toolbox crash.
I tried uninstalling and reinstalling Toolbox and deleting the two files "mod and pro activator" and installing them again.
Minecraft version is 1.0.8.
The latest version of toolbox support Minecraft 1.0.8.
Please tell me what to do this client is awesome.

**Comment by Vertex-Client** [comment]
Hey there, I'm currently trying to investigate this issue. Could you please send the crash message? You can get it on the crash dialog (the dialog that says Toolbox has stopped working). Click on 'report', then system information (should be a small text at the bottom of the screen), then click on stack trace and send me that log. Thanks in advance. :)

PS: Try removing all Vertex data files too (remove vertexclientpenew.txt, vertexclientpe_categories_new.txt, etc. in games/com.mojang/minecraftpe folder). Also remove data & cache for Toolbox in Android settings. :)

**Comment by aboudshi-da7a** [comment]
Toolbox just crash without displaying anything.
Like you said I used ES file explorer pro and deleted all the file that are related to Vertex Client in games, com.mojang, deleted the Vertex mod, downloaded them again, erased the data and cache of toolbox.
I ran toolbox and chose the mod.
I opened a world and the mod gave me the same message but it worked.
I closed toolbox and opened toolbox and ran the mod again and again and it is still working.
The problem is solved.
Thank you man for this amazing mod.
Keep up the amazing work 👍👍👍

**Comment by Vertex-Client** [comment]
Good to know that it's fixed!

PS: We're working on the next release which will probably be a final release of Vertex. We're not sure about what version number it will have, maybe v2.3.1, maybe v2.4. But it will contain many tweaks & bug fixes. :)
