### ISSUE TITLE
Translation/language support

### ISSUE THREAD

**Issue by gitdhimg** [Vertex-Client/Vertex-Client-PE#60]
I don't know if I should be asking this here, but since I don't know how to contact you guys. Is it okay if I make a translated version for my friends? Or could you guys ask Astro36 to translate it since my friends are Korean.

**Comment by Astro36** [comment]
I forgot it, sorry. I will make the language support feature, but i don't know how many time will spend.

**Comment by Astro36** [comment]
Language support feature was merged into master branch. You can help to make translated version on vertex client.
For more information: [README.md](https://github.com/Vertex-Client/Vertex-Client-PE/blob/master/lang/README.md)
