### ISSUE TITLE
What do i do?

### ISSUE THREAD

**Issue by frbdgbfgsb** [Vertex-Client/Vertex-Client-PE#63]
My block launcher (normal+pro) keeps crashing everytime I use the 2.4v, MCMRARM ( the creator of toolbox,) has removed the launcher options, so toolbox is as good as dead, and MCPE master is useless. Can you recommend any launchers?
Mcpe version: 1.2.1 (beta)
Device: lenovo tab 10 A7600
Android: 4.4.2
Vertex client: 2.4v
Toolbox version: latest at time of writing
Block launcher version: latest at time of writing

**Comment by frbdgbfgsb** [comment]
BTW before toolbox removed its launcher options the client was awesome! I terrorised the servers XD

**Comment by Vertex-Client** [comment]
Thank you, but this issue should be fixed in the next (pre-)release which will be released today or within a few days. The 'Pro' Activator isn't supported anymore.
