### ISSUE TITLE
Can't break blocks with client enabled

### ISSUE THREAD

**Issue by AlekEagle** [Vertex-Client/Vertex-Client-PE#64]
I simply can't break blocks with the client enabled I have to turn on instant break and that won't work on servers.
How to reproduce: Simply activate the client.
I'm using Kindle fire 5th gen,
BL version: 1.17.8,
Launcher: Blocklauncher free,
Pro: no,
MCPE version: 1.2.8.
Android version: 5.1.1
Problem description: almost acts like I'm punching an entity's hitbox accompanied by the entity punch sound.

**Comment by AlekEagle** [comment]
Before I rule this out as a bug, I will try toolbox.

**Comment by Vertex-Client** [comment]
Could you please check out the Prevent mod? Breaking blocks may be prevented because the 'Prevent breaking blocks' option is on.

**Comment by AlekEagle** [comment]
Ok P.S. toolbox won't work
