### ISSUE TITLE
Explosions don't work

### ISSUE THREAD

**Issue by Delkarix** [Vertex-Client/Vertex-Client-PE#69]
I noticed that you are still using Level.explode(x, y, z, size) in the TapExplosion mod. Level.explode(x, y, z, size) no longer works and is depreciated. Use explode(x, y, z, size) instead.

**Comment by Delkarix** [comment]
~I forgot to mention: Phase mod is also broken. It allows me to see a kind of x-ray effect but does not allow me to noclip through blocks.~
Edit by Vertex Client: please create another issue for this.

**Comment by Vertex-Client** [comment]
Thanks for reporting this. We'll look into it.
