### ISSUE TITLE
Restart failure

### ISSUE THREAD

**Issue by NovaAssistant** [Vertex-Client/Vertex-Client-PE#80]
Hi, I've been attempting to install vertex, and I've pinned down the issue stopping me from doing so to vertex's innablility to restart during installation, how do I fix this?

**Comment by NovaAssistant** [comment]
Oh boy an I Impatient

**Comment by NovaAssistant** [comment]
Am*

**Comment by Founderroni** [comment]
wdym

**Comment by Vertex-Client** [comment]
Before we can help, you need to provide us with some details. Please refer to the [instructions on how to report an issue](https://github.com/Vertex-Client/Vertex-Client-PE/issues/34).

_Please take notice that Vertex hasn't been updated yet to support Android 10_

**Comment by NovaAssistant** [comment]
System: Android 9
Mcpe version:1.14.1
BlockLauncher:1.27
Vertex client:3.1
I would give a in depth explaination of how I got here, but I've tampered with it so much to try and get it to work I don't know how to replicate it

**Comment by Founderroni** [comment]
Disable the client, load the game until start menu shows up then enable vertex.

**Comment by Founderroni** [comment]
This happened when I used 3.1, in 3.2 I don't need to do that so I would guess that you wouldn't need to either.

**Comment by NovaAssistant** [comment]
Is 3.2 public?

**Comment by Founderroni** [comment]
Yes, it's a dev build so it's just a plain .js instead of .modpkg

**Comment by NovaAssistant** [comment]
Where can I get it?

**Comment by Founderroni** [comment]
The github page... Or the website but it takes u to the page.
