### ISSUE TITLE
How to download?

### ISSUE THREAD

**Issue by starwarsfanhere** [Vertex-Client/Vertex-Client-PE#86]

**Comment by xLPMG** [comment]
Hellostarwarsfanhere, open the releases web page (https://github.com/Vertex-Client/Vertex-Client-PE/releases/). You'll find the latest release right at the top. If you scroll to the bottom of that release, you'll have the option to download the Vertex_Client_PE.modpkg file or the source code .zip that contains the .js file. Just select the right file for your ModPE launcher. I hope, I was able to help you.

~LPMG
