### ISSUE TITLE
How to download 

### ISSUE THREAD

**Issue by kobdaz** [Vertex-Client/Vertex-Client-PE#87]
Cant see a download button. Help?

**Comment by FakexET** [comment]
I can't find how to download it

**Comment by xLPMG** [comment]
Hello kobdaz and FakexET, open the releases web page (https://github.com/Vertex-Client/Vertex-Client-PE/releases/). You'll find the latest release right at the top. If you scroll to the bottom of that release, you'll have the option to download the Vertex_Client_PE.modpkg file or the source code .zip that contains the .js file. Just select the right file for your ModPE launcher. I hope, I was able to help you.

~LPMG

**Comment by xLPMG** [comment]
Issue closed for now.
